[workspace]
# members = ["webtarot_server", "webtarot_protocol", "tarotgame", "webtarot_bot"]
members = ["webtarot_server", "webtarot_protocol", "webtarot_client", "tarotgame", "webtarot_bot"]
exclude = ["bacasable"]
