# (Required) The locale/language identifier of the language used in the source
# code.
fallback_language = "en"


# (Optional) Use the gettext localization system.
[gettext]
# (Required) The locales that the software will be translated into.
target_languages = ["fr"]
# (Required) Path to the output directory, relative to `i18n.toml` of the crate
# being localized.
output_dir = "i18n"
